spring:
  application:
    name: coupon-gateway
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/

zuul:
  prefix: /api
  routes:
    templates:
      path: /coupon-template/**
      serviceId: eureka-client-coupon-template
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000